# Generated by Django 5.1.7 on 2025-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='_vulnerabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='screenshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='current_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
