# Generated by Django 5.1.7 on 2025-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan__summary_scan__vulnerabilities_scan_screenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='_summary',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='_vulnerabilities',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='scan',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
